### ISSUE TITLE
More flexible inputs

### ISSUE THREAD

**Issue by kozross** [Liqwid-Labs/plutarch-quickcheck#1]
Currently, our strategy for property testing involves a workflow similar to this:

1. Generate inputs at the Haskell level using QuickCheck machinery.
2. `pconstant` them up to Plutarch to determine whether we succeed or fail.
3. If we fail, use QuickCheck shrinkers, again, at the Haskell level.

There's multiple additional steps elided here, but it's basically the overall view. This has many benefits: we can re-use a lot of QuickCheck capabilities (such as counterexample reporting, coverage, etc), we limit the amount of work done at the Plutarch level (which is slow and tedious by comparison), and familiarity with QuickCheck rapidly translates into familiarity with the helpers.

However, it does force us into an unfortunate corner where _any_ input type must have a `PConstantDecl` instance. For 'singular' inputs, this isn't usually a problem: either we already have a `Data` encoding (which basically means we get this 'for free') or the type is simple enough that there's already an instance available (say, `Integer`). However, we frequently want to have 'non-singular' inputs, such as tuples and lists. Currently, this is rather annoying:

* We can have pairs (which `pconstant` into `PBuiltinPair`), but not larger tuples;
* Lists `pconstant` into `PBuiltinList`;
* Such lifts have much less friendly APIs (`PBuiltinPair` is especially obnoxious);
* For our own, more complex, types, we have to define `PConstantDecl` and `PUnsafeLiftDecl`, which is tedious, annoying, and also can easily be wrong.

While none of these are per-se dealbreakers, even in writing the examples in this repo, I found myself running up against these limitations fairly fast. It's also bad when you need 'structured inputs', which more complex tests quickly begin to require. Lastly, there are cases where we want to test functions whose inputs aren't types that can be `pconstant`ed into; working around this isn't pleasant.

So why can't we just use the machinery to produce `Term`s directly? The issue amounts to needing something like this:

```haskell
weCan'tWriteThis :: Gen (forall (s :: S) . Term s (PPair PInteger PInteger))
```

The reason is that we have to generate _closed_ Plutarch terms, or else we can't `compile` the result. This is remarkably difficult to prove to GHC, as it requires impredicative instantiation, which is notoriously brittle. Even the most recent work on `ImpredicativeTypes` (which we do have available!) is [woefully inadequate to this task](https://gitlab.haskell.org/ghc/ghc/-/issues/18126): specifically, we don't have lists of impredicatively-typed elements or do-notation involving impredicativity! While we _could_ work around the lack of do-notation (although _I_ certainly wouldn't want to write non-trivial generators without it), lack of lists breaks us all the way apart, as we _have_ to make use of this:

```haskell
oneof :: forall (a :: Type) . [Gen a] -> Gen a
```

Substituting `a` with `forall (s :: S) . Term s PInteger` shows the resulting issue wonderfully.

I'm not actually sure what to do about this, or whether it's enough of a problem to worry about. It's _possible_ that if the listed QuickLook issues are fixed, we can do this, but I'm skeptical, partly because some functionality would require 'returning a skolem': for example, consider classifier functions:

```haskell
weWouldNeedThis :: SomethingFinite -> Gen (forall (s :: S) . Term s PInteger)
```

While I'm not 100% sure QuickLook _couldn't_ deal with this, I'm not confident that it _could_ deal with this either, especially not in a way that's reasonable or usable.

**Comment by kozross** [comment]
One solution I just thought of is to have multiple versions of `peqProperty` and `classifiedProperty` which take multiple generated arguments. However, this is ultimately not very scalable and raises issues of its own.

**Comment by peter-mlabs** [comment]
Can we write a `PGen` and generate the value within Plutarch itself?

**Comment by kozross** [comment]
That _is_ an option, but it's a _lot_ of work.

**Comment by peter-mlabs** [comment]
Hypothetically (given infinite time and resources), would there be downsides to this approach that you know of?

**Comment by kozross** [comment]
None that I can immediately think of, other than 'it might be very slow because the CEK machine simulator is slow'. I do have another workaround idea that would be both simpler _and_ not require re-implementing everything, but I'd have to check if it works.

**Comment by cjay** [comment]
A newtype-wrapper seems to work fine for this:
```Haskell
newtype ClosedTerm' (t :: S -> Type) = ClosedTerm' (forall (s :: S). Term s t)

instance Show (ClosedTerm' t) where
  show = const "meh"

pairTermGen :: Gen (ClosedTerm' (PBuiltinPair PInteger PInteger))
pairTermGen = do
  a <- Gen.chooseInt (0, 10)
  b <- Gen.chooseInt (0, 10)
  pure $ ClosedTerm' $ pconstant (fromIntegral a, fromIntegral b)

test :: Property
test = forAll pairTermGen $ \(ClosedTerm' pair) ->
  let script = compile $ pfstBuiltin # pair
      (res, _, _) = evalScript script
   in isRight res
```

**Comment by kozross** [comment]
Resolved in the most recent PQ. Closing.
