### ISSUE TITLE
Add instances?

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutarch-quickcheck#13]
Should this library (or a companion library) include instances for common types, such as those found [here](https://github.com/MangoIV/seabug-plutarch/blob/mangoiv/plutarch-mob-programming/onchain/test/Seabug/Gen.hs)?

**Comment by kozross** [comment]
We already do some such instances. I think if these are Plutus-related, then they definitely do belong, but it also requires canonical Plutarch lifts, which not everything has yet.

**Comment by peter-mlabs** [comment]
Closed as stale
