### ISSUE TITLE
`classifiedProperty`: `getOutcome` could make good use of the input class

### ISSUE THREAD

**Issue by cjay** [Liqwid-Labs/plutarch-quickcheck#17]
The ergonomics of `classifiedProperty` and `classifiedPropertyNative` could be improved by passing the class to the input function that computes the expected result (`getOutcome`).
In many cases `getOutcome` has to re-implement checks that are done in the classifier anyway, at least when there are classes that should always result in failure. While users of the native version can work around this by manually calling the classifier in `getOutcome`, users of the non-native version can not. However, even the workaround is sub-optimal, since running the classifier again is wasteful. `classifiedProperty` and `classifiedPropertyNative` always run the classifier anyway before doing anything else, in order to check that `gen` behaves correctly.

Passing the class to the shrinker could also be beneficial, in order to give it the shrinker a chance to shrink more efficiently, without producing a huge number of shrinkings that change the class and have to be rejected.

**Comment by peter-mlabs** [comment]
closed as stale
