### ISSUE TITLE
Missing functionality in module Property: dealing with parallel implementations

### ISSUE THREAD

**Issue by cjay** [Liqwid-Labs/plutarch-quickcheck#18]
One testing strategy that can potentially save a lot of work when testing a Plutarch function:
- Create a Haskell implementation of the Plutarch function, even if it's not needed in off-chain code.
- Test various properties on the output of the Haskell version only (let's call this the functional properties)
- Test output of the Haskell version and the Plutarch version for equality (let's call this the equality property)
--> the various properties automatically hold for the Plutarch version as well

To execute this strategy, it is crucial that inputs for both implementations of the function are generated in the exact same way. 

One way this could be achieved by running both implementations in every `Property` and including the equality check along with the functional property being tested. The library could provide helper functions for this. 

Another way would be to create a separately run `Property`, where equality of the outputs of both versions get checked. This has extra difficulty and potential for mistakes attached to it. The input generator of this equality property has to reliably recreate the inputs in the same way as ALL of the input generators used in the actual functional properties that get tested on the Haskell version only. If multiple different input generators are in use for the functional properties, it might be best to have multiple copies of of the equality property, each using one of the different input generators. Helper functions could be provided to reduce the potential for mistakes and omissions when doing this.

`classifiedProperty` and `classifiedPropertyNative` complicate the second way even more, because their class-based behavior is currently only available for use with Plutarch functions, and recreating what they do for Haskell functions needlessly risks generating inputs differently. If it is decided that the second way should be supported, the classification-based functionality of `classifiedProperty` needs to be decoupled from the Plutarch-specific things it does, decomposed into two functions. Since the classification-based functionality has absolutely nothing to do with Plutarch, this should happen anyway.

**Comment by peter-mlabs** [comment]
closed as stale
