### ISSUE TITLE
Minor Nix build issue

### ISSUE THREAD

**Issue by jhodgdev** [Liqwid-Labs/plutarch-quickcheck#2]
When I try and build the flake with `nix-direnv`, I get this issue:
```
❯ touch .envrc
direnv: loading ~/repos/plutarch-quickcheck/.envrc                                                                                
direnv: using flake
fetching Git repository 'https://gitlab.homotopic.tech/nix/lint-utils.git'fatal: couldn't find remote ref refs/heads/spec-type
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
direnv: renewed cache
direnv: export +AR +AS +CABAL_CONFIG +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_GHC_LIBDIR +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_PKG_CONFIG_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_STORE +NM +OBJCOPY +OBJDUMP +PKG_CONFIG +PKG_CONFIG_PATH +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +buildInputs +buildPhase +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +exactDeps +installPhase +name +nativeBuildInputs +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH ~XDG_DATA_DIRS
```
Thankfully, `nix-direnv` still enters the environment fine and `cabal build`, `cabal test` don't have any issues. Running `nix develop` doesn't show any warnings.

**Comment by kozross** [comment]
I'm unfamiliar with `nix-direnv`, as I always use `nix develop` followed by `cabal` stuff. How would I go about fixing this?

**Comment by jhodgdev** [comment]
Unsure, I assumed it was the result of a dodgy `flake` but occurs to me now it might be the fault of `nix-direnv`. I am updating it now to see if the problem keeps up.

**Comment by jhodgdev** [comment]
Doesn't appear to have fixed it but at the same time, isn't _blocking_ anything (touch wood :deciduous_tree:). Haven't seen this in any other repo.

**Comment by srid** [comment]
> fetching Git repository 'https://gitlab.homotopic.tech/nix/lint-utils.git'fatal: couldn't find remote ref refs/heads/spec-type

This branch got deleted accidentally. Actually, I'm super curious where this input is even being used? For linting/formating I'd recommend https://github.com/numtide/treefmt

**Comment by kozross** [comment]
@jhodgdev Would you be OK PRing a solution to this? I don't really know how it works, and don't use `nix-direnv` at all.

**Comment by jhodgdev** [comment]
Yeah, I'd be happy to work on it except similar to what @srid said, I do not know how to identify which input is causing the problem.

**Comment by srid** [comment]
@jhodgdev Can you test with Plutarch branch `srid/lint-utils-fix` from https://github.com/Plutonomicon/plutarch/pull/467? IIUC this is the same as https://github.com/srid/emanote/issues/279

**Comment by emiflake** [comment]
I have been able to reproduce this locally too. It only happens with `nix-direnv`. 

Simply nuking `flake.lock` isn't enough to fix it, but I can confirm @srid's branch fixes it on my end with:
```diff
-  inputs.plutarch.url = "github:Plutonomicon/plutarch/staging";
+  inputs.plutarch.url = "github:Plutonomicon/plutarch/srid/lint-utils-fix";
```
And *also* nuking `flake.lock`. I guess we'll just have to wait for that PR to get merged.

**Comment by kozross** [comment]
Let me know when the PR lands and I'll fix it up.

**Comment by jhodgdev** [comment]
Thanks for this @emiflake and @kozross !
