### ISSUE TITLE
Missing functionality in module Property: beyond equality

### ISSUE THREAD

**Issue by cjay** [Liqwid-Labs/plutarch-quickcheck#20]
Equality of outputs with expected values is only one of many needed predicates. A flexible way of specifying the predicate is needed.

Example property for a Haskell function:
```
propShrinkGain :: (Permutation, [Integer]) -> Property
propShrinkGain (p, ell) =
  let permuted = ell `permuteBy` p
   in (sort <$> permuted) === (Just . sort $ ell)
```
Here, both the input list and the permuted list get compared for "sorted equality", to make sure no elements have been added or removed. If only equality is supported by the helper functions from this library, a sorting function has to be implemented in Plutarch just to be able to do this test.

Testing certain invariants on the output might not involve any kind of equality at all. Access to the input is definitely needed too.

**Comment by cjay** [comment]
I should also add that sorting in Plutarch turned out to have an enormous memory budget cost, due to creation of intermediate lists, as well as even just iterating over a list, all counting against the budget. Having this as part of the test severely limits the memory budget of the actual function being tested. A workaround would be allowing the user to specify increased budget sizes for the test.

**Comment by peter-mlabs** [comment]
closed as stale
